configType = "standard-overrides"
l1ChainID = 1337
fundDevAccounts = true
opcmAddress = "0x9611b3093e7d02269cd9277eee5c8a93e9188c5d"
superchainConfigProxy = "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9"
l1ContractsLocator = "file:///app/packages/contracts-bedrock/forge-artifacts"
l2ContractsLocator = "file:///app/packages/contracts-bedrock/forge-artifacts"

[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000000000c3"
  baseFeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  l1FeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  sequencerFeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  operatorFeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  eip1559DenominatorCanyon = 1000000000
  eip1559Denominator = 100000000
  eip1559Elasticity = 1
  gasLimit = 60000000
  operatorFeeScalar = 0
  operatorFeeConstant = 0
  daFootprintGasScalar = 1  # DA footprint gas scalar for optimizing block packing rate after Jovian, default 400
  [chains.deployOverrides]
      l2GenesisBlockGasLimit = "0xC845880"
      l2GenesisBlockBaseFeePerGas = "0x5FC01C5"
      l2BlockTime = 1
      sequencerWindowSize = 7200
      faultGameClockExtension = 5
      faultGameMaxClockDuration = 20
      l2GenesisJovianTimeOffset = "0x0"      # Jovian fork activation
      l2GenesisKarstTimeOffset = "0x3c"      # Karst fork activation (added for demo)
  [chains.roles]
    l1ProxyAdminOwner = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    l2ProxyAdminOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    systemConfigOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    unsafeBlockSigner = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
    batcher = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    proposer = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    challenger = "0x7d18A1B858253b5588f61fb5739d52e4b84e2cdA"
  [chains.customGasToken]
    enabled = true
    name = "OKB"
    symbol = "OKB"
    InitialLiquidity = "0x0" # 0 OKB, no premint
